### ISSUE TITLE
MigraDocCore.* NuGet-Packages depend on earliest PdfSharpCore version, which leads to a NullReferenceExcpetion

### ISSUE THREAD

**Issue by manuelfuchs** [ststeiger/PdfSharpCore#170]
# MigraDocCore.* NuGet-Packages depend on earliest PdfSharpCore version, which leads to a NullReferenceExcpetion

The NuGet-Packages [MigraDocCore.Rendering](https://www.nuget.org/packages/MigraDocCore.Rendering/0.1.1) and [MigraDocCore.DocumentObjectModel](https://www.nuget.org/packages/MigraDocCore.DocumentObjectModel/0.1.1) are currently available in version `0.1.1`, whilst your other [PdfSharpCore package](https://www.nuget.org/packages/PdfSharpCore/1.2.17) is available in version `1.2.17`.
Additionally, your latest MigraDocCore packages are depending on version `>=0.1.1` of PdfSharpCore.

When I install MigraDocCore.DocumentObjectModel and inspect its dependencies, Visual Studio informs me that it tries to load its PdfSharpCore dependency, however, since there exists no version `0.1.1` of PdfSharpCore, the lowest matching version is fetched, which is version `1.0.0`.
![image](https://user-images.githubusercontent.com/13959511/130068543-a6aa36fc-16ae-4152-9f29-9f200065892e.png)

When I now try to create a new instance of `MigraDocCore.DocumentObjectModel.Document`, a NullReferenceException is thrown.

## Question

Is the version label intentionally at version `0.1.1`?

## Reproduction steps:
* Create a new CLI project targeting .NET 5.0
* Install [MigraDocCore.DocumentObjectModel](https://www.nuget.org/packages/MigraDocCore.DocumentObjectModel/0.1.1)
* Copy the following code into `Program.cs`
```c#
using MigraDocCore.DocumentObjectModel;

var document = new Document();
```

## Stacktrace
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MigraDocCore.DocumentObjectModel.Styles.SetupStyles()
   at MigraDocCore.DocumentObjectModel.Styles..ctor(DocumentObject parent)
   at MigraDocCore.DocumentObjectModel.Document..ctor()
   at <Program>$.<Main>$(String[] args)
```

**Comment by manuelfuchs** [comment]
I just saw #147 which seemed related, can I help resolving issue?

**Comment by startnow65** [comment]
Yes please @manuelfuchs 
Seems direct project reference (from MigraDocCore to PdfSharpCore) does not play well with nuget package resolution process.

I think the `0.1.1` version is just some "default" version since [the reference](https://github.com/ststeiger/PdfSharpCore/blob/master/MigraDocCore.DocumentObjectModel/MigraDocCore.DocumentObjectModel.csproj#L28) is not a Package reference.

**Comment by manuelfuchs** [comment]
@startnow65 I forked your repository and set the version numbers manually for each project via the `Version` property in each .csproj file. Having project dependencies does not hurt, when using `dotnet pack` after building all projects, this command is able to detect that it depends on a package and is able to resolve this.
For example, when inspecting the generated .nuspec file with NuGet package explorer, you can see that the project reference is correctly resolved.
![image](https://user-images.githubusercontent.com/13959511/130190633-e3cc936d-820e-40e1-99c7-779356588805.png)

However, I am not quite sure if that will work with your CI pipeline, since you are already declaring the version number in the `ProductVersionInfo.cs` file, however it is somehow only applied to the main project, `PdfSharpCore`?
Since it looks like you are applying the version in your CI pipeline, you could also pass the version can with the /p:Version=$(Build.BuildNumber) parameter in your build pipeline ([according to this](https://katlimruiz.medium.com/how-to-autogenerate-a-nuget-package-and-specify-the-version-d12f17d6bfb8)), but I don't know how to integrate this.
