### ISSUE TITLE
System.ArgumentOutOfRangeException: Non-negative number required on PDFs larger than two gigabyte

### ISSUE THREAD

**Issue by jhofer-arian** [ststeiger/PdfSharpCore#193]
Hi I'm having issues reading pdfs that are larger than two gigs due to an integer overflow.

The following Stack is thrown:
`
   System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'value')
      at System.IO.FileStream.set_Position(Int64 value)
      at PdfSharp.Pdf.IO.Lexer.ReadRawString(Int32 position, Int32 length)
      at PdfSharp.Pdf.IO.Parser.ReadTrailer()
      at PdfSharp.Pdf.IO.PdfReader.Open(Stream stream, String password, PdfDocumentOpenMode openmode, PdfPasswordProvider passwordProvider)
      at PdfSharp.Pdf.IO.PdfReader.Open(String path, String password, PdfDocumentOpenMode openmode, PdfPasswordProvider provider)
`

Maybe I'm calling something wrong when reading the file with `PdfReader.Open()`, but to me it looks like an integer overflow.

**Comment by ststeiger** [comment]
That's probably because Int.MaxValue is 2,147,483,647, which is around 2 GiBs.
You'll have to change the int32 with int64. 

Why is your PDF larger than two GB ? 
Now correct me if I'm wrong, but that doesn't sound so reasonable.

**Comment by jhofer-arian** [comment]
I'm working in print and most artworks are provided in PDF, those artworks are then printed on rather large banners and therefor the artworks contain a lot of information. We have written a tool which reads a few of those PDF Parameters using this library for which are then used for further processing of those products.
