### ISSUE TITLE
Create xImage object from memory stream doesn't work

### ISSUE THREAD

**Issue by Ervin304** [ststeiger/PdfSharpCore#348]
I can't create an xImage object from the MemoryStream of a png image I get from Azure blob storage.
I always get IvalidFormatException.

The problem are these lines (PdfSharpCore.Utils.ImageSharpImageSource.cs)

 using (var stream = imageStream.Invoke())
            {
                var image = Image.Load<TPixel>(stream, out IImageFormat imgFormat);
                return new ImageSharpImageSourceImpl<TPixel>(name, image, (int)quality, imgFormat is PngFormat);
            }

You should implement somethink like this:

 using (var MemoryStream= imageStream.Invoke())
            {
                var image = Image.Load<TPixel>(stream.ToArray(), out IImageFormat imgFormat);
                return new ImageSharpImageSourceImpl<TPixel>(name, image, (int)quality, imgFormat is PngFormat);
            }

**Comment by redtalon616** [comment]
Error occurs when running the following code:
                MemoryStream strm = new MemoryStream();
                img.Save(strm, System.Drawing.Imaging.ImageFormat.Png);
                strm.Position = 0;

                PdfSharpCore.Drawing.XImage pdfimage = PdfSharpCore.Drawing.XImage.FromStream(() => strm);


Error details:
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'SixLabors.ImageSharp.Image`1<!!0> SixLabors.ImageSharp.Image.Load(System.IO.Stream, SixLabors.ImageSharp.Formats.IImageFormat ByRef)'.
  Source=PdfSharpCore
  StackTrace:
   at PdfSharpCore.Utils.ImageSharpImageSource`1.FromStreamImpl(String name, Func`1 imageStream, Nullable`1 quality)
   at MigraDocCore.DocumentObjectModel.MigraDoc.DocumentObjectModel.Shapes.ImageSource.FromStream(String name, Func`1 imageStream, Nullable`1 quality)
   at PdfSharpCore.Drawing.XImage..ctor(Func`1 stream)
   at PdfSharpCore.Drawing.XImage.FromStream(Func`1 stream)
   at AppElectricianToolbox.Pages.CustomerView.CreateEditAM2.<PrintDisplay>d__75.MoveNext() in C:\Users\marty\OneDrive\Desktop\AppElectricianToolbox\AppElectricianToolbox\Pages\CustomerView\CreateEditAM2.razor:line 917

**Comment by Iceeman76** [comment]
I have the same problem. Any news regarding this?
