### ISSUE TITLE
ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Fill()

### ISSUE THREAD

**Issue by Ervin304** [ststeiger/PdfSharpCore#367]
After upgrading to 1.3.57, I received the following error message when reading a pdf document (it worked fine in version 1.3.28):

Exception: Unexpected EOF
at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Fill()
at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Read(Byte[] buffer, Int32 offset, Int32 count)
at PdfSharpCore.Pdf.Filters.FlateDecode.Decode(Byte[] data, FilterParms parms)
at PdfSharpCore.Pdf.Filters.Filtering.Decode(Byte[] data, PdfItem filterItem, PdfItem decodeParms)
at PdfSharpCore.Pdf.Advanced.PdfContent.Decode()
at PdfSharpCore.Pdf.Advanced.PdfContent..ctor(PdfDictionary dict)
at PdfSharpCore.Pdf.PdfPage.get_Contents()

**Comment by toolgood** [comment]
https://github.com/ststeiger/PdfSharpCore/issues/451 The same issue
