### ISSUE TITLE
PdfSharpCore.Drawing.XImage.FromFile Error

### ISSUE THREAD

**Issue by 3400442579** [ststeiger/PdfSharpCore#401]
System.MissingMethodException: Method not found: 'SixLabors.ImageSharp.Image`1<!!0> SixLabors.ImageSharp.Image.Load(System.String, SixLabors.ImageSharp.Formats.IImageFormat ByRef)'.
   at PdfSharpCore.Utils.ImageSharpImageSource`1.FromFileImpl(String path, Nullable`1 quality)
   at MigraDocCore.DocumentObjectModel.MigraDoc.DocumentObjectModel.Shapes.ImageSource.FromFile(String path, Nullable`1 quality)
   at PdfSharpCore.Drawing.XImage..ctor(String path)
   at PdfSharpCore.Drawing.XImage.FromFile(String path, PdfReadAccuracy accuracy)
   at PdfSharpCore.Drawing.XImage.FromFile(String path)

``` var document = new PdfDocument();
            var page = document.AddPage();
            var gfx = PdfSharpCore.Drawing.XGraphics.FromPdfPage(page);
            gfx.DrawImage(PdfSharpCore.Drawing.XImage.FromFile(@"E:\Dev\Copyright\Web\zdoc\1\signature.png"), new PdfSharpCore.Drawing.XPoint(0, 0));
            document.Save(Path.Combine(path, "signature.pdf"));
```

**Comment by LewxX** [comment]
I also had this issue, you can fix it by downgrading you SixLabors.ImageSharp version to 2.*
`<PackageReference Include="SixLabors.ImageSharp" Version="2.*" />`
or I guess the merge request could fix it, if someone would accept it: #400

**Comment by alexariza95** [comment]
still not fixed this, I had to patch it myself so I could use the last version of the library. You just need to extend the class ImageSource as he did with ImageSharpImageSource. The bug is in this method that changed in the lasts upgrades of the library: SixLabors.ImageSharp.Image.Load now only accepts ONE parameter instead of two.

`protected override IImageSource FromBinaryImpl(string name, Func<byte[]> imageSource, int? quality = 75)
{
    ArgumentNullException.ThrowIfNull(imageSource);

    var source = imageSource();
    Image image = Image.Load(source);
    return new ImageSharpImageSourceImplementation(name, image, quality.Value, image.Metadata.DecodedImageFormat is PngFormat);
}`

Here´s an example of an override method I extended in my new class.
