### ISSUE TITLE
Cannot insert image.

### ISSUE THREAD

**Issue by IngoManthey** [ststeiger/PdfSharpCore#434]
In the previous versions I had no problems with the following code.
`ImageSource.ImageSourceImpl ??= new ImageSharpImageSource<Rgba32>();
 header.AddImage(ImageSource.FromFile(Invoice.Image));`

Now I get the following exception:
System.MissingMethodException: Method not found: 'SixLabors.ImageSharp.Image`1<!!0> SixLabors.ImageSharp.Image.Load(System.IO.Stream, SixLabors.ImageSharp.Formats.IImageFormat ByRef)'.
   at PdfSharpCore.Utils.ImageSharpImageSource`1.FromStreamImpl(String name, Func`1 imageStream, Nullable`1 quality)
   at MigraDocCore.DocumentObjectModel.MigraDoc.DocumentObjectModel.Shapes.ImageSource.FromStream(String name, Func`1 imageStream, Nullable`1 quality)
   at PdfSharpCore.Drawing.XImage..ctor(Func`1 stream)
   at PdfSharpCore.Drawing.XImage.FromStream(Func`1 stream)

Can someone help me?

**Comment by balkarov** [comment]
I have the same problem. Any solution?

**Comment by mtarlac** [comment]
#426

**Comment by chrisg32** [comment]
@balkarov @IngoManthey  Reference SixLabors.ImageSharp 2.1.7

**Comment by balkarov** [comment]
@chrisg32  I already use ImageSharp version 3.X

**Comment by chrisg32** [comment]
@IngoManthey That solution has work for me and a few others. Do you have any other projects in your solution that are referencing a higher version of image sharp?

I would suggest taking a look at the thread on #426 . @TonyValenti created a fork that adds support for the new image sharp. That could be an alternative for you until the package maintainers accept PR #427

**Comment by chrisg32** [comment]
@IngoManthey If you want to use 3.1.3 then you will need to use the fork mentioned in #426 or wait for PR #427.
