### ISSUE TITLE
Threading issue GlyphTypefaceCache Dictionary

### ISSUE THREAD

**Issue by hwayan** [ststeiger/PdfSharpCore#44]
I'm creating pdfs from a web service and it looks like there might be an issue with multi-threading for the dictionary in GlyphTypefaceCache. Currently, I can only reproduce it sometimes while running tests, probably due to the race condition nature of it. I understand Dictionaries aren't thread-safe so I wonder if it's something that should be replaced by something like ConcurrentDictionary.

Here's the stacktrace:
```System.ArgumentException : An item with the same key has already been added. Key: tk:arial/n/400/5
Stack Trace:
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at PdfSharpCore.Fonts.OpenType.GlyphTypefaceCache.AddGlyphTypeface(XGlyphTypeface glyphTypeface)
   at PdfSharpCore.Drawing.XGlyphTypeface.GetOrCreateFrom(String familyName, FontResolvingOptions fontResolvingOptions)
   at PdfSharpCore.Drawing.XFont.Initialize()```

**Comment by jamesmblair** [comment]
I have also reproduced this while running parallel async code in unit tests. I agree that a thread-safe dictionary implementation like ConcurrentDictionary would likely resolve the issue.

Are you open to contributions by pull request? I'm happy to work on a fix for this.

**Comment by ststeiger** [comment]
@jamesmblair: Sure, just send me the pull request.
