### ISSUE TITLE
Encoding 1252 error in .net core project

### ISSUE THREAD

**Issue by dnnbuddy** [ststeiger/PdfSharpCore#61]
I am getting the following error in my stacktrace. Please help me in resolving the above issue.

`Unhandled exception. System.NotSupportedException: No data is available for encoding 1252. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at PdfSharp.Pdf.Internal.PdfEncoders.get_WinAnsiEncoding()
   at PdfSharp.Fonts.OpenType.OpenTypeDescriptor.Initialize()
   at PdfSharp.Fonts.OpenType.OpenTypeDescriptor..ctor(String fontDescriptorKey, XFont font)
   at PdfSharp.Fonts.FontDescriptorCache.GetOrCreateDescriptorFor(XFont font)
   at PdfSharp.Drawing.XFont.CreateDescriptorAndInitializeFontMetrics()
   at PdfSharp.Drawing.XFont.Initialize()
   at PdfSharp.Drawing.XFont..ctor(String familyName, Double emSize, XFontStyle style, XPdfFontOptions pdfOptions)
   at MigraDoc.Rendering.FontHandler.FontToXFont(Font font, PdfFontEncoding encoding)
   at MigraDoc.Rendering.ParagraphRenderer.get_CurrentFont()
   at MigraDoc.Rendering.ParagraphRenderer.CalcCurrentVerticalInfo()
   at MigraDoc.Rendering.ParagraphRenderer.InitFormat(Area area, FormatInfo previousFormatInfo)
   at MigraDoc.Rendering.ParagraphRenderer.Format(Area area, FormatInfo previousFormatInfo)
   at MigraDoc.Rendering.TopDownFormatter.FormatOnAreas(XGraphics gfx, Boolean topLevel)
   at MigraDoc.Rendering.FormattedCell.Format(XGraphics gfx)
   at MigraDoc.Rendering.TableRenderer.FormatCells()
   at MigraDoc.Rendering.TableRenderer.InitFormat(Area area, FormatInfo previousFormatInfo)
   at MigraDoc.Rendering.TableRenderer.Format(Area area, FormatInfo previousFormatInfo)
   at MigraDoc.Rendering.TopDownFormatter.FormatOnAreas(XGraphics gfx, Boolean topLevel)
   at MigraDoc.Rendering.FormattedTextFrame.Format(XGraphics gfx)
   at MigraDoc.Rendering.TextFrameRenderer.Format(Area area, FormatInfo previousFormatInfo)
   at MigraDoc.Rendering.TopDownFormatter.FormatOnAreas(XGraphics gfx, Boolean topLevel)
   at MigraDoc.Rendering.FormattedCell.Format(XGraphics gfx)
   at MigraDoc.Rendering.TableRenderer.FormatCells()
   at MigraDoc.Rendering.TableRenderer.InitFormat(Area area, FormatInfo previousFormatInfo)
   at MigraDoc.Rendering.TableRenderer.Format(Area area, FormatInfo previousFormatInfo)
   at MigraDoc.Rendering.TopDownFormatter.FormatOnAreas(XGraphics gfx, Boolean topLevel)
   at MigraDoc.Rendering.FormattedHeaderFooter.Format(XGraphics gfx)
   at MigraDoc.Rendering.FormattedDocument.FormatHeader(HeaderFooterPosition hfp, HeaderFooter header)
   at MigraDoc.Rendering.FormattedDocument.FormatHeadersFooters()
   at MigraDoc.Rendering.FormattedDocument.MigraDoc.Rendering.IAreaProvider.GetNextArea()
   at MigraDoc.Rendering.TopDownFormatter.FormatOnAreas(XGraphics gfx, Boolean topLevel)
   at MigraDoc.Rendering.FormattedDocument.Format(XGraphics gfx)
   at MigraDoc.Rendering.DocumentRenderer.PrepareDocument()
   at MigraDoc.Rendering.PdfDocumentRenderer.PrepareDocumentRenderer(Boolean prepareCompletely)
   at MigraDoc.Rendering.PdfDocumentRenderer.PrepareRenderPages()
   at MigraDoc.Rendering.PdfDocumentRenderer.RenderDocument()
   at Invoicer.Services.Impl.PdfInvoice.Save(String filename, String password)`

**Comment by ststeiger** [comment]
If you looked at the example, or did a simple google search, you would have found:

You need to register the codepage provider at program startup.  

```
public void ConfigureServices(IServiceCollection services)
{
    Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
 
    // more code here
}
```

**Comment by dnnbuddy** [comment]
Complete explanation. Not an issue with the lib. Thanks,
