### ISSUE TITLE
MissingManifestResourceException at read pdf.

### ISSUE THREAD

**Issue by ukiuni** [ststeiger/PdfSharpCore#71]
When read a pdf, I found this Exception occure.
```
PdfSharpCore.Pdf.IO.PdfReaderException: UNEXPECTED ERROR while formatting message with ID UnexpectedToken: System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "PdfSharpCore.Resources.Messages.resources" was correctly embedded or linked into assembly "PdfSharpCore" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at PdfSharpCore.PSSR.GetString(PSMsgID id)
   at PdfSharpCore.PSSR.Format(PSMsgID id, Object[] args)
   at PdfSharpCore.Internal.ParserDiagnostics.ThrowParserException(String message)
   at PdfSharpCore.Pdf.IO.Parser.ReadObject(PdfObject pdfObject, PdfObjectID objectID, Boolean includeReferences, Boolean fromObjecStream)
   at PdfSharpCore.Pdf.IO.PdfReader.Open(Stream stream, String password, PdfDocumentOpenMode openmode, PdfPasswordProvider passwordProvider)
{$... and my codes}
```

and I not found PdfSharpCore/Resources/Messages.resources in this repository.
Is this correct?

**Comment by TontonTij** [comment]
Hello,
I have the same issue.
Have you found a solution?
Thanks

Below my exception:

```
UNEXPECTED ERROR while formatting message with ID UnexpectedToken: System.Resources.MissingManifestResourceException: Could not find the resource "PdfSharpCore.Resources.Messages.resources" among the resources "" embedded in the assembly "PdfSharpCore", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.Resources.ResourceManager.GetString(String name)
   at PdfSharpCore.PSSR.GetString(PSMsgID id)
   at PdfSharpCore.PSSR.Format(PSMsgID id, Object[] args)
   at PdfSharpCore.Internal.ParserDiagnostics.ThrowParserException(String message)
   at PdfSharpCore.Pdf.IO.Parser.ReadObject(PdfObject pdfObject, PdfObjectID objectID, Boolean includeReferences, Boolean fromObjecStream)
   at PdfSharpCore.Pdf.IO.PdfReader.Open(Stream stream, String password, PdfDocumentOpenMode openmode, PdfPasswordProvider passwordProvider)
   at PdfSharpCore.Pdf.IO.PdfReader.Open(Stream stream, String password, PdfDocumentOpenMode openmode)
   at PdfSharpCore.Pdf.IO.PdfReader.Open(Stream stream, PdfDocumentOpenMode openmode)
```

**Comment by davidpene** [comment]
Also seeing this issue
```
System.Resources.MissingManifestResourceException: 
Could not find any resources appropriate for the specified culture or the neutral culture. 
Make sure \"PdfSharpCore.Resources.Messages.resources\" was correctly embedded 
or linked into assembly \"PdfSharpCore\" at compile time, 
or that all the satellite assemblies required are loadable and fully signed.
```

Any updates?

**Comment by ststeiger** [comment]
Fixed it a minute ago.
