### ISSUE TITLE
System.DllNotFoundException Unable to load shared library 'libgdiplus'

### ISSUE THREAD

**Issue by sunnyatticsoftware** [ststeiger/PdfSharpCore#82]
I am finding an error when running some unit tests in Gitlab CI/CD pipeline using a docker container.

I am using `mcr.microsoft.com/dotnet/core/sdk:3.1` and apparently that SDK (and also other versions) does not have certain libraries needed at runtime such as `libgdiplus` and directories such as  `/usr/share/fonts/truetype`.

Do you think this has an easy fix? Happy to look into it if it makes sense to you the error and you think it can be avoided without installing any additional thing in the docker container.

Thanks

```
   Error Message:
   System.TypeInitializationException : The type initializer for 'PdfSharpCore.Utils.FontResolver' threw an exception.
---- System.IO.DirectoryNotFoundException : Could not find a part of the path '/usr/share/fonts/truetype'.
  Stack Trace:
     at PdfSharpCore.Utils.FontResolver..ctor()
   at Sasw.PdfGenerator.PdfService..ctor() in /builds/sunnyatticsoftware/sasw-aforo-manager/src/Sasw.PdfGenerator/PdfService.cs:line 21
   at Sasw.PdfGenerator.UnitTests.PdfServiceTests.ConstructorTests.Given_Valid_Dependencies_When_Constructing_Instance.When() in /builds/sunnyatticsoftware/sasw-aforo-manager/test/Sasw.PdfGenerator.UnitTests/PdfServiceTests/ConstructorTests.cs:line 21
   at Sasw.TestSupport.Given_When_Then_Test.Setup()
   at Sasw.TestSupport.Given_When_Then_Test..ctor()
   at Sasw.PdfGenerator.UnitTests.PdfServiceTests.ConstructorTests.Given_Valid_Dependencies_When_Constructing_Instance..ctor()
----- Inner Stack Trace -----
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at PdfSharpCore.Utils.FontResolver..cctor()
  X Sasw.PdfGenerator.UnitTests.PdfServiceTests.ConstructorTests+Given_Valid_Dependencies_When_Constructing_Instance.Then_It_Should_Have_Created_A_Valid_Instance [1ms]
  Error Message:
   System.TypeInitializationException : The type initializer for 'PdfSharpCore.Utils.FontResolver' threw an exception.
---- System.IO.DirectoryNotFoundException : Could not find a part of the path '/usr/share/fonts/truetype'.
  Stack Trace:
     at PdfSharpCore.Utils.FontResolver..ctor()
   at Sasw.PdfGenerator.PdfService..ctor() in /builds/sunnyatticsoftware/sasw-aforo-manager/src/Sasw.PdfGenerator/PdfService.cs:line 21
   at Sasw.PdfGenerator.UnitTests.PdfServiceTests.ConstructorTests.Given_Valid_Dependencies_When_Constructing_Instance.When() in /builds/sunnyatticsoftware/sasw-aforo-manager/test/Sasw.PdfGenerator.UnitTests/PdfServiceTests/ConstructorTests.cs:line 21
   at Sasw.TestSupport.Given_When_Then_Test.Setup()
   at Sasw.TestSupport.Given_When_Then_Test..ctor()
   at Sasw.PdfGenerator.UnitTests.PdfServiceTests.ConstructorTests.Given_Valid_Dependencies_When_Constructing_Instance..ctor()
----- Inner Stack Trace -----
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at PdfSharpCore.Utils.FontResolver..cctor()
  X Sasw.PdfGenerator.UnitTests.PdfServiceTests.GetPdfTests+Given_An_Image_And_Text_Lines_When_Getting_Pdf.Then_It_Should_Return_A_Valid_Stream [1ms]
  Error Message:
   System.TypeInitializationException : The type initializer for 'PdfSharpCore.Utils.FontResolver' threw an exception.
---- System.IO.DirectoryNotFoundException : Could not find a part of the path '/usr/share/fonts/truetype'.
  Stack Trace:
     at PdfSharpCore.Utils.FontResolver..ctor()
   at Sasw.PdfGenerator.PdfService..ctor() in /builds/sunnyatticsoftware/sasw-aforo-manager/src/Sasw.PdfGenerator/PdfService.cs:line 21
   at Sasw.PdfGenerator.UnitTests.PdfServiceTests.GetPdfTests.Given_An_Image_And_Text_Lines_When_Getting_Pdf.Given() in /builds/sunnyatticsoftware/sasw-aforo-manager/test/Sasw.PdfGenerator.UnitTests/PdfServiceTests/GetPdfTests.cs:line 20
   at Sasw.TestSupport.Given_When_Then_Test.Setup()
   at Sasw.TestSupport.Given_When_Then_Test..ctor()
   at Sasw.PdfGenerator.UnitTests.PdfServiceTests.GetPdfTests.Given_An_Image_And_Text_Lines_When_Getting_Pdf..ctor()
----- Inner Stack Trace -----
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at PdfSharpCore.Utils.FontResolver..cctor()
  X Sasw.PdfGenerator.UnitTests.PdfServiceTests.GetPdfTests+Given_An_Image_And_Text_Lines_When_Getting_Pdf.Then_It_Should_Have_The_Position_Set_To_Zero [1ms]
  Error Message:
   System.TypeInitializationException : The type initializer for 'PdfSharpCore.Utils.FontResolver' threw an exception.
---- System.IO.DirectoryNotFoundException : Could not find a part of the path '/usr/share/fonts/truetype'.
  Stack Trace:
     at PdfSharpCore.Utils.FontResolver..ctor()
   at Sasw.PdfGenerator.PdfService..ctor() in /builds/sunnyatticsoftware/sasw-aforo-manager/src/Sasw.PdfGenerator/PdfService.cs:line 21
   at Sasw.PdfGenerator.UnitTests.PdfServiceTests.GetPdfTests.Given_An_Image_And_Text_Lines_When_Getting_Pdf.Given() in /builds/sunnyatticsoftware/sasw-aforo-manager/test/Sasw.PdfGenerator.UnitTests/PdfServiceTests/GetPdfTests.cs:line 20
   at Sasw.TestSupport.Given_When_Then_Test.Setup()
   at Sasw.TestSupport.Given_When_Then_Test..ctor()
   at Sasw.PdfGenerator.UnitTests.PdfServiceTests.GetPdfTests.Given_An_Image_And_Text_Lines_When_Getting_Pdf..ctor()
----- Inner Stack Trace -----
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at PdfSharpCore.Utils.FontResolver..cctor()
```

**Comment by sunnyatticsoftware** [comment]
I tried to support only one font and embed the `ttf` in the application itself thinking that I could avoid the library from requesting local resources such as `/usr/share/fonts/truetype`  within the SDK Core container, because it does not exist, or the `libgdiplus`, but **no luck. Same exceptions**.

```
public class CustomFontResolver
    : IFontResolver
{
    public FontResolverInfo ResolveTypeface(string familyName, bool isBold, bool isItalic)
    {
        if (familyName.Equals(FontConstants.FontFamily, StringComparison.CurrentCultureIgnoreCase))
        {
            if (isBold && isItalic)
            {
                return new FontResolverInfo(FontConstants.BoldItalic);
            }

            if (isBold)
            {
                return new FontResolverInfo(FontConstants.Bold);
            }

            if (isItalic)
            {
                return new FontResolverInfo(FontConstants.Italic);
            }

            return new FontResolverInfo(FontConstants.Regular);
        }

        throw new KeyNotFoundException($"Font family {familyName} not supported");
    }

    public byte[] GetFont(string faceName)
    {
        using var memoryStream = new MemoryStream();
        using var fileStream = File.Open($"Fonts/{faceName}", FileMode.Open);
        fileStream.CopyTo(memoryStream);
        memoryStream.Position = 0;
        var bytes = memoryStream.ToArray();
        return bytes;
    }

    public string DefaultFontName { get; } = FontConstants.FontFamily;
}
```

and setting the font resolver with:
```
GlobalFontSettings.FontResolver = new CustomFontResolver();
```

My question remains, if anybody knows any workaround to have this working without those directories and file system libraries..
They don't seem to be part of the .net core framework.

**Comment by sunnyatticsoftware** [comment]
I saw the "problem".
Even though a Custom Font Resolver can be set from the beginning, the built-in `FontResolver` is already there and it has the following in a static constructor:
```
bool isLinux = System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.Linux);
if (isLinux)
{
    fontDir = "/usr/share/fonts/truetype/";
    SSupportedFonts = Directory.GetFiles(fontDir, "*.ttf", SearchOption.AllDirectories);
    SetupFontsFiles(SSupportedFonts);
    return;
}
```

So my statement `GlobalFontSettings.FontResolver.GetType();` is causing a read at the file system level. And since some OS or docker containers won't have the folder `/usr/share/fonts/truetype/`, it fails.

Don't have much time today to investigate further. But I think a possible solution could be to have the `SSupportedFonts` and `SetupFontsFiles(SSupportedFonts)` lazy loaded only the first time any of the methods that need them is used.

Another possible solution could be not to have this static or not to assign FontResolver from the beginning.

**Any preference or advice... I'm happy to help and create a merge request.**

**Comment by sunnyatticsoftware** [comment]
I resolved the issue by having a docker image for the DotNetCore SDK or AspNetCore with `libgdiplus` installed on it. That seems to add also a `/usr/share/fonts/truetype` so the above is not an issue anymore
https://hub.docker.com/repository/docker/sunnyatticsoftware/dotnet-core-aspnet-libgdiplus
https://hub.docker.com/repository/docker/sunnyatticsoftware/dotnet-core-sdk-libgdiplus
